#!/usr/bin/env bash

cd /home/kamilyousuf/.config/home-manager
git add -u
([ -z $1 ] 2>/dev/null && git commit -m "home-manager: $(date +%F--%T)") || git commit -m "$(date +%F--%T): \"home-manager: $1\""
git push
home-manager switch
