#!/usr/bin/env bash

cd ~/nixfiles
git add . 
([ -z $1 ] 2>/dev/null && git commit -m "$(date +%F--%T)") || git commit -m "$(date +%F--%T): \"home-manager: $1\""
git push
home-manager switch --impure
