#!/usr/bin/env bash

cd ~/.config/home-manager
# git add -u
nix flake update
# sudo home-manager switch && git commit -m "$(date +%F--%T): flake update" && git push
home-manager switch
success=$?
if [ $success -eq 0 ]; then
    # git add -A ':!./flake.lock'
    git commit -m "$(date +%F--%T): flake update" && git push
else
    # revert to the older flake until the world stops ending
    echo -e "\"home-manager switch\" failed: see error logs"
    git restore ~/.config/home-manager/flake.lock
fi

# home-manager switch
# /home/kamilyousuf/nixfiles/scripts/hmb "update"
