#!/usr/bin/env bash

cd ~/nixfiles
new_pull=$(git pull)
is_flake_update=$(grep "${new_pull}" ~/nixfiles/flake.lock)
echo -e "Running ${is_flake_update}\n"
cmd="switch"
if [ ! -z $is_flake_update ]; then
    cmd="boot"
fi
sudo nixos-rebuild $cmd --show-trace
status=$?
if [ $status -eq 0 ]; then
    git add -u
    ([ -z $1 ] 2>/dev/null && git commit -m "$(date +%F--%T)") || git commit -m "$(date +%F--%T): \"$1\""
    git push
else
    echo -e "'nixos-rebuild switch' failed: not committing changes"
fi
# git push
