#!/usr/bin/env bash

cd ~/nixfiles
git add -u
nix flake update
git add -u
sudo nixos-rebuild boot && git commit -m "$(date +%F--%T): flake update" && git push
# git push
# sudo nixos-rebuild boot
hmu
